/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AddressBookWorkshop;

public class AddressBookExecutor {
    public static void main(String[] args) {
    	System.out.println("Welcome to Address Book Workshop!!!");
    	System.out.println("Add contact details here");
    }
}
